

create table usuarios (
id integer NOT NULL AUTO_INCREMENT,
    nome character varying(255) NOT NULL,
    email character varying(90) NOT NULL,
    senha character varying(20) NOT NULL,
    celular character varying(22) NOT NULL,
    cep character varying(12) NOT NULL,
    bairro character varying(20) NOT NULL,
    primary key(id)
);

create table fretes (
id integer NOT NULL AUTO_INCREMENT,
titulo varchar(30) NOT NULL,
descricao varchar(128) NOT NULL,
endereco varchar(40) NOT NULL,
cep varchar(12) NOT NULL,
cel varchar(22) NOT NULL,
primary key(id)

);
alter table fretes add constraint fk7nh5b6gcy7eloqs2i5o7a5gwx foreign key (usuario_id) references usuarios;

create table fretes (id int4 generated by default as identity, cel varchar(255), cep varchar(255), descricao varchar(255), endereco varchar(255), titulo varchar(255), usuario_id int4, primary key (id))
create table usuarios (id int4 generated by default as identity, bairro varchar(255), celular varchar(255), cep varchar(255), email varchar(255), nome varchar(255), senha varchar(255), primary key (id))
alter table if exists fretes add constraint FK7nh5b6gcy7eloqs2i5o7a5gwx foreign key (usuario_id) references usuarios
create table fretes (id int4 generated by default as identity, cel varchar(255), cep varchar(255), descricao varchar(255), endereco varchar(255), titulo varchar(255), usuario_id int4, primary key (id))
create table usuarios (id int4 generated by default as identity, bairro varchar(255), celular varchar(255), cep varchar(255), email varchar(255), nome varchar(255), senha varchar(255), primary key (id))
alter table if exists fretes add constraint FK7nh5b6gcy7eloqs2i5o7a5gwx foreign key (usuario_id) references usuarios
create table fretes (id int4 generated by default as identity, cel varchar(255), cep varchar(255), descricao varchar(255), endereco varchar(255), titulo varchar(255), usuario_id int4, primary key (id))
create table usuarios (id int4 generated by default as identity, bairro varchar(255), celular varchar(255), cep varchar(255), email varchar(255), nome varchar(255), senha varchar(255), primary key (id))
alter table if exists fretes add constraint FK7nh5b6gcy7eloqs2i5o7a5gwx foreign key (usuario_id) references usuarios
